$color = rgba(18, 16, 28, 1.0)
$inner_color = rgba(18, 16, 28, 0.8)
$outer_color = rgba(225, 90, 72, 1.0)
$font_color = rgba(240, 196, 168, 1.0)
$placeholder_color = rgba(240, 196, 168, 0.7)
$check_color = rgba(240, 180, 90, 1.0)
